project_id = "jhjhzwbvmkurwfohjxlu"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000", "https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_changes = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = true

[functions.share-document]
verify_jwt = false

[functions.send-tenant-email]
verify_jwt = false

[studio]
enabled = true
port = 54323

[edge-runtime]
enabled = true
port = 54327

[realtime]
enabled = true
port = 54328